version: '3'
services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8080:8069"  # Cambiado de 8069 a 8080 (formato: "puerto_host:puerto_contenedor")
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:15
    ports:
      - "5433:5432"  # Añadido para exponer PostgreSQL en puerto 5433 en lugar de 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
